version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: db123
  app:
    image: my-node-app:v1
    ports:
      - 5000:3000